name: cs229-shortcut-detection
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - pyyaml
  - pytest
  - pytorch
  - torchvision
  - pip
  - pip:
      - torchxrayvision
      - grad-cam
      - pydicom
      - redivis
